# Generated by Django 5.0.4 on 2024-04-25 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AactivoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActivoMueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Adeudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('intereses', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('por_periodo', models.CharField(choices=[('semanal', 'semanal'), ('mensual', 'mensual'), ('quincenal', 'quincenal'), ('diario', 'diario'), ('anual', 'anual')], default='mensual', max_length=50)),
                ('estado', models.CharField(choices=[('hecho', 'hecho'), ('en_espera', 'en_espera'), ('anulado', 'anulado'), ('finalizado', 'finalizado'), ('en_perioro', 'en_periodo')], default='en_perioro', max_length=50)),
                ('primer_pago', models.DateField(default=datetime.date(2024, 4, 25))),
                ('ultimo_pago', models.DateField(default=datetime.date(2024, 4, 25))),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fecha_de_cobro', models.DateField(default=datetime.date(2024, 4, 25))),
                ('estado', models.CharField(choices=[('hecho', 'hecho'), ('en_espera', 'en_espera'), ('anulado', 'anulado'), ('finalizado', 'finalizado'), ('en_perioro', 'en_periodo')], default='en_espera', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GananicasTotalesHistorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='GastoImprevisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GastosTotalesHistorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='PasivoAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.CharField(choices=[('hecho', 'hecho'), ('en_espera', 'en_espera'), ('anulado', 'anulado'), ('finalizado', 'finalizado'), ('en_perioro', 'en_periodo')], default='en_perioro', max_length=50)),
                ('fecha_de_primer_pago', models.DateField(default=datetime.date(2024, 4, 25))),
                ('por_tiempo', models.CharField(default='indefinido', max_length=50)),
                ('ultima_fecha', models.DateField(default=datetime.date(2024, 4, 25))),
                ('veces', models.IntegerField(default=0)),
            ],
        ),
    ]
