# Generated by Django 5.0.4 on 2024-04-25 07:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('apellido_materno', models.CharField(default='', max_length=100)),
                ('apellido_paterno', models.CharField(default='', max_length=100)),
                ('fecha_de_nacimiento', models.DateField(default=datetime.date(2024, 4, 25))),
                ('salario', models.DecimalField(decimal_places=2, default=248.98, max_digits=9)),
                ('fecha_de_primer_paga', models.DateField(default=datetime.date(2024, 4, 25))),
                ('modo_periodo_de_paga', models.CharField(choices=[('semanal', 'semanal'), ('quincenal', 'quincenal'), ('diario', 'diario'), ('anual', 'anual')], default='semanal', max_length=50)),
                ('fecha_de_entrada', models.DateField(default=datetime.date(2024, 4, 25))),
            ],
        ),
        migrations.CreateModel(
            name='Socias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('apellido_materno', models.CharField(default='', max_length=100)),
                ('apellido_paterno', models.CharField(default='', max_length=100)),
                ('aportado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('participacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ganancias_totales_historicas', models.DecimalField(decimal_places=0.0, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='GaffetDeEmpleada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.empleada')),
            ],
        ),
    ]
