# Generated by Django 5.0.4 on 2024-04-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socias',
            name='ganancias_totales_historicas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
