# Generated by Django 5.0.4 on 2024-04-26 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_socias_ganancias_totales_historicas'),
    ]

    operations = [
        #migrations.RenameField(
        #    model_name='socias',
        #    old_name='apellido_panerno',
        #    new_name='apellido_paterno',
        #),
        migrations.AlterField(
            model_name='empleada',
            name='fecha_de_entrada',
            field=models.DateField(default=datetime.date(2024, 4, 26)),
        ),
        migrations.AlterField(
            model_name='empleada',
            name='fecha_de_nacimiento',
            field=models.DateField(default=datetime.date(2024, 4, 26)),
        ),
        migrations.AlterField(
            model_name='empleada',
            name='fecha_de_primer_paga',
            field=models.DateField(default=datetime.date(2024, 4, 26)),
        ),
    ]
