# Generated by Django 5.0.4 on 2024-04-26 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_de_entrega',
            field=models.DateField(default=datetime.date(2024, 4, 26)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_de_pedido',
            field=models.DateField(default=datetime.date(2024, 4, 26)),
        ),
    ]
